global using DeFuncto;
global using DeFuncto.Extensions;
global using Xunit;
global using Nvx.ConsistentAPI;
global using static Nvx.ConsistentAPI.Types;
global using static DeFuncto.Prelude;
global using DeFuncto.Assertions;
global using Nvx.ConsistentAPI.TestUtils;
global using TestModel = TestEventModel.TestEventModel;
global using TestEventModel;
