global using DeFuncto;
global using DeFuncto.Extensions;
global using Xunit;
global using Nvx.ConsistentAPI;
global using Nvx.ConsistentAPI.Configuration.Settings;
global using Nvx.ConsistentAPI.EventModeling;
global using Nvx.ConsistentAPI.FileUploads;
global using Nvx.ConsistentAPI.RecurringTasks;
global using Nvx.ConsistentAPI.Idempotency;
global using Nvx.ConsistentAPI.Errors;
global using Nvx.ConsistentAPI.Logging;
global using Nvx.ConsistentAPI.SignalR;
global using Nvx.ConsistentAPI.Security;
global using Nvx.ConsistentAPI.ValidationRules;
global using Nvx.ConsistentAPI.Framework.Commands;
global using Nvx.ConsistentAPI.Framework.Entities;
global using Nvx.ConsistentAPI.Framework.Events;
global using Nvx.ConsistentAPI.Framework.Serialization;
global using static Nvx.ConsistentAPI.Types;
global using static DeFuncto.Prelude;
