# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore ./src/Nvx.ConsistentAPI.sln
      - name: Build Framework
        run: dotnet build -c Release --no-restore ./src/Nvx.ConsistentAPI/Nvx.ConsistentAPI.csproj
      - name: Test
        working-directory: ./src/Nvx.ConsistentAPI.Tests
        run: dotnet test --no-restore
      - name: Package Framework
        run: dotnet pack -c Release -o . ./src/Nvx.ConsistentAPI/Nvx.ConsistentAPI.csproj
      - name: Publish Framework
        if: github.ref == 'refs/heads/main'
        run: dotnet nuget push **/Release/**/Nvx.ConsistentAPI*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Build Test Utils
        run: dotnet build -c Release --no-restore ./src/Nvx.ConsistentAPI.TestUtils/Nvx.ConsistentAPI.TestUtils.csproj
      - name: Package Test Utils
        run: dotnet pack -c Release -o . ./src/Nvx.ConsistentAPI.TestUtils/Nvx.ConsistentAPI.TestUtils.csproj
      - name: Publish Test Utils
        if: github.ref == 'refs/heads/main'
        run: dotnet nuget push **/Release/**/Nvx.ConsistentAPI.TestUtils*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
